Gambar Pertama


In [2]:
from google.colab import files
import io

upload_files = files.upload()

Saving Ikan-Mas-Ikan-Air-Tawar-yang-Mudah-di-Budidaya-1.jpg to Ikan-Mas-Ikan-Air-Tawar-yang-Mudah-di-Budidaya-1.jpg


In [3]:
import cv2

citra = cv2.imread("Ikan-Mas-Ikan-Air-Tawar-yang-Mudah-di-Budidaya-1.jpg")

In [4]:
citra = cv2.cvtColor(citra, cv2.COLOR_BGR2GRAY)

In [5]:
ret,thresh = cv2.threshold(citra,150,255,0)

In [6]:
contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_NONE)

In [7]:
cnt = contours[1]
M = cv2.moments(cnt)

In [8]:
Hm = cv2.HuMoments(M)

In [9]:
print(Hm[0][0])

0.5462962962984521


In [10]:
print("Hu-Moments of second contour:\n", Hm)

Hu-Moments of second contour:
 [[5.46296296e-01]
 [2.55229767e-01]
 [4.70710765e-02]
 [3.85357923e-02]
 [1.64122902e-03]
 [1.91912178e-02]
 [7.31763723e-06]]


Gambar Kedua

In [11]:
from google.colab import files
import io

upload_files = files.upload()

Saving medium_2431efa05dda158e79408d0c1f93c25b.png to medium_2431efa05dda158e79408d0c1f93c25b.png


In [12]:
citra2 = cv2.imread("medium_2431efa05dda158e79408d0c1f93c25b.png")

In [13]:
citra2 = cv2.cvtColor(citra2, cv2.COLOR_BGR2GRAY)

In [14]:
ret,thresh = cv2.threshold(citra2,150,255,0)

In [15]:
contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_NONE)

In [16]:
cnt2 = contours[1]
M2 = cv2.moments(cnt2)

In [17]:
Hm2 = cv2.HuMoments(M2)

In [18]:
print("Hu-Moments of second contour:\n", Hm2)

Hu-Moments of second contour:
 [[ 2.61234488e-01]
 [ 3.97658080e-02]
 [ 6.31463246e-04]
 [ 5.30362727e-05]
 [-9.70584901e-09]
 [-1.05761573e-05]
 [ 2.40323084e-16]]


Gambar 3

In [19]:
from google.colab import files
import io

upload_files = files.upload()

Saving cara-budidaya-ikan-nila-dengan-kolam-terpal-untuk-pemula-di-rumah-1.jpg to cara-budidaya-ikan-nila-dengan-kolam-terpal-untuk-pemula-di-rumah-1.jpg


In [20]:
citra3 = cv2.imread("cara-budidaya-ikan-nila-dengan-kolam-terpal-untuk-pemula-di-rumah-1.jpg")
citra3 = cv2.cvtColor(citra3, cv2.COLOR_BGR2GRAY)
ret,thresh = cv2.threshold(citra3,150,255,0)
contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_NONE)
cnt3 = contours[1]
M3 = cv2.moments(cnt3)
Hm3 = cv2.HuMoments(M3)
print("Hu-Moments of second contour:\n", Hm3)

Hu-Moments of second contour:
 [[ 2.22222223e-01]
 [ 1.23456790e-02]
 [ 5.48685745e-03]
 [ 2.19468016e-04]
 [-2.40834495e-07]
 [-2.43853351e-05]
 [-2.59791601e-11]]


Gambar 4

In [21]:
from google.colab import files
import io

upload_files = files.upload()

Saving 1.-BUDIDAYA-IKAN-NILA.jpg to 1.-BUDIDAYA-IKAN-NILA.jpg


In [22]:
citra4 = cv2.imread("1.-BUDIDAYA-IKAN-NILA.jpg")
citra4 = cv2.cvtColor(citra4, cv2.COLOR_BGR2GRAY)
ret,thresh = cv2.threshold(citra4,150,255,0)
contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_NONE)
cnt4 = contours[1]
M4 = cv2.moments(cnt4)
Hm4 = cv2.HuMoments(M4)
print("Hu-Moments of second contour:\n", Hm4)

Hu-Moments of second contour:
 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


Gambar 5

In [23]:
from google.colab import files
import io

upload_files = files.upload()

Saving Ikan-Nila-680x350.jpg to Ikan-Nila-680x350.jpg


In [24]:
citra5 = cv2.imread("1.-BUDIDAYA-IKAN-NILA.jpg")
citra5 = cv2.cvtColor(citra5, cv2.COLOR_BGR2GRAY)
ret,thresh = cv2.threshold(citra5,150,255,0)
contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_NONE)
cnt5 = contours[1]
M5 = cv2.moments(cnt5)
Hm5 = cv2.HuMoments(M5)
print("Hu-Moments of second contour:\n", Hm5)

Hu-Moments of second contour:
 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


Gambar 6

In [28]:
from google.colab import files
import io

upload_files = files.upload()

Saving VIER PFOTEN_2019-03-15_001-2886x1999-1920x1330.jpg to VIER PFOTEN_2019-03-15_001-2886x1999-1920x1330 (1).jpg


In [29]:
citra6 = cv2.imread("VIER PFOTEN_2019-03-15_001-2886x1999-1920x1330.jpg")
citra6 = cv2.cvtColor(citra6, cv2.COLOR_BGR2GRAY)
ret,thresh = cv2.threshold(citra6,150,255,0)
contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_NONE)
cnt6 = contours[1]
M6 = cv2.moments(cnt6)
Hm6 = cv2.HuMoments(M6)
print("Hu-Moments of second contour:\n", Hm6)

Hu-Moments of second contour:
 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


Gambar 7

In [53]:
from google.colab import files
import io

upload_files = files.upload()

Saving puppy-dog-mc-230321-03-b700d4.jpg to puppy-dog-mc-230321-03-b700d4.jpg


In [54]:
citra7 = cv2.imread("puppy-dog-mc-230321-03-b700d4.jpg")
citra7 = cv2.cvtColor(citra7, cv2.COLOR_BGR2GRAY)
ret,thresh = cv2.threshold(citra7,150,255,0)
contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_NONE)
cnt7 = contours[1]
M7 = cv2.moments(cnt7)
Hm7 = cv2.HuMoments(M7)
print("Hu-Moments of second contour:\n", Hm7)

Hu-Moments of second contour:
 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [55]:
import pandas as pd #menggabungkan data moment Hu dari setiap foto
dataset1= pd.DataFrame({"jenis" : "ikan", "Hu1" : Hm[0],"Hu2" : Hm[1],"Hu3" : Hm[2], "Hu4" : Hm[3],"Hu5" : Hm[4],"Hu6" : Hm[5],"Hu7" : Hm[6]})
dataset2= pd.DataFrame({"jenis" : "ikan", "Hu1" : Hm2[0],"Hu2" : Hm2[1],"Hu3" : Hm2[2], "Hu4" : Hm2[3],"Hu5" : Hm2[4],"Hu6" : Hm2[5],"Hu7" : Hm2[6]})
dataset3= pd.DataFrame({"jenis" : "ikan", "Hu1" : Hm3[0],"Hu2" : Hm3[1],"Hu3" : Hm3[2], "Hu4" : Hm3[3],"Hu5" : Hm3[4],"Hu6" : Hm3[5],"Hu7" : Hm3[6]})
dataset4= pd.DataFrame({"jenis" : "ikan", "Hu1" : Hm4[0],"Hu2" : Hm4[1],"Hu3" : Hm4[2], "Hu4" : Hm4[3],"Hu5" : Hm4[4],"Hu6" : Hm4[5],"Hu7" : Hm4[6]})
dataset5= pd.DataFrame({"jenis" : "ikan", "Hu1" : Hm5[0],"Hu2" : Hm5[1],"Hu3" : Hm5[2], "Hu4" : Hm5[3],"Hu5" : Hm5[4],"Hu6" : Hm5[5],"Hu7" : Hm5[6]})
dataset6= pd.DataFrame({"jenis" : "puppy", "Hu1" : Hm6[0],"Hu2" : Hm6[1],"Hu3" : Hm6[2], "Hu4" : Hm6[3],"Hu5" : Hm6[4],"Hu6" : Hm6[5],"Hu7" : Hm6[6]})
dataset7= pd.DataFrame({"jenis" : "puppy", "Hu1" : Hm7[0],"Hu2" : Hm7[1],"Hu3" : Hm7[2], "Hu4" : Hm7[3],"Hu5" : Hm7[4],"Hu6" : Hm7[5],"Hu7" : Hm7[6]})

In [66]:
dataset = pd.concat([dataset1, dataset2, dataset3, dataset4, dataset5, dataset6, dataset7], axis=0)

In [67]:
dataset.to_csv("moment_hu.csv", index=False)

Mengaplikasikan Machine learning klasifikasi untuk prediksi gambar berdasarkan Moment Hu

In [68]:
dataset = pd.get_dummies(dataset) #mentransformasi data kategorikal menjadi numerikal

In [69]:
dataset

Hu1       Hu2       Hu3       Hu4           Hu5       Hu6  \
0  0.546296  0.255230  0.047071  0.038536  1.641229e-03  0.019191   
0  0.261234  0.039766  0.000631  0.000053 -9.705849e-09 -0.000011   
0  0.222222  0.012346  0.005487  0.000219 -2.408345e-07 -0.000024   
0  0.000000  0.000000  0.000000  0.000000  0.000000e+00  0.000000   
0  0.000000  0.000000  0.000000  0.000000  0.000000e+00  0.000000   
0  0.000000  0.000000  0.000000  0.000000  0.000000e+00  0.000000   
0  0.000000  0.000000  0.000000  0.000000  0.000000e+00  0.000000   

            Hu7  jenis_ikan  jenis_puppy  
0  7.317637e-06           1            0  
0  2.403231e-16           1            0  
0 -2.597916e-11           1            0  
0  0.000000e+00           1            0  
0  0.000000e+00           1            0  
0  0.000000e+00           0            1  
0  0.000000e+00           0            1

In [70]:
from sklearn.model_selection import train_test_split
X = dataset.iloc[:, [0,1,2,3,4,5,6]].values
y = dataset.iloc[:, [7]].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0) #perbandingan test : train = 2 : 8

In [71]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [73]:
import numpy as np
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 0]
 [1 1]]


/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [74]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[0 1]
 [0 1]]


0.5

Source Image : https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.rumah.com%2Fpanduan-properti%2Fbudidaya-ikan-nila-44902&psig=AOvVaw3XLhp2fIyRhvKunXuKi2aS&ust=1680745483348000&source=images&cd=vfe&ved=0CBEQjhxqFwoTCNDU9v_Okf4CFQAAAAAdAAAAABAJ 

https://thegorbalsla.com/ikan-nila/


https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.ruparupa.com%2Fblog%2Fcara-budidaya-ikan-nila-mudah-dan-menguntungkan%2F&psig=AOvVaw3XLhp2fIyRhvKunXuKi2aS&ust=1680745483348000&source=images&cd=vfe&ved=0CBEQjhxqFwoTCNDU9v_Okf4CFQAAAAAdAAAAABAR

mostly sources are from google